/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OcRouteImport } from './routes/oc'
import { Route as CtRouteImport } from './routes/ct'
import { Route as IndexRouteImport } from './routes/index'

const OcRoute = OcRouteImport.update({
  id: '/oc',
  path: '/oc',
  getParentRoute: () => rootRouteImport,
} as any)
const CtRoute = CtRouteImport.update({
  id: '/ct',
  path: '/ct',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ct': typeof CtRoute
  '/oc': typeof OcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ct': typeof CtRoute
  '/oc': typeof OcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ct': typeof CtRoute
  '/oc': typeof OcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ct' | '/oc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ct' | '/oc'
  id: '__root__' | '/' | '/ct' | '/oc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CtRoute: typeof CtRoute
  OcRoute: typeof OcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oc': {
      id: '/oc'
      path: '/oc'
      fullPath: '/oc'
      preLoaderRoute: typeof OcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ct': {
      id: '/ct'
      path: '/ct'
      fullPath: '/ct'
      preLoaderRoute: typeof CtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CtRoute: CtRoute,
  OcRoute: OcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
